server:
  port: 8080

spring:
  application:
    name: ManageAttendance

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        use_sql_comments: true

  mvc:
    problemdetails:
      enabled: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8

logging:
  level:
    root: INFO
    com.ddd.manage_attendance: DEBUG
    org.springframework.web: DEBUG

google:
  auth:
    client-id: ${GOOGLE_CLIENT_ID:}
    client-secret: ${GOOGLE_CLIENT_SECRET:}
    redirect-uri: ${GOOGLE_REDIRECT_URI:}

apple:
  auth:
    service-id: ${APPLE_SERVICE_ID:}
    redirect-uri: ${APPLE_REDIRECT_URI:}
    team-id: ${APPLE_TEAM_ID:}
    key-id: ${APPLE_KEY_ID:}
    private-key: ${APPLE_PRIVATE_KEY:}

jwt:
  secret: ${JWT_SECRET:}
  access-token-validity-in-seconds: 43200 # 12 hours
  refresh-token-validity-in-seconds: 1209600 # 14 days