server:
  forward-headers-strategy: framework

spring:
  application:
    name: ManageAttendance
  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false 

logging:
  level:
    root: INFO

google:
  auth:
    client-id: ${GOOGLE_CLIENT_ID:}
    client-secret: ${GOOGLE_CLIENT_SECRET:}
    redirect-uri: ${GOOGLE_REDIRECT_URI:}

apple:
  auth:
    service-id: ${APPLE_SERVICE_ID:}
    redirect-uri: ${APPLE_REDIRECT_URI:}

jwt:
  secret: ${JWT_SECRET:}
  access-token-validity-in-seconds: 43200 # 12 hours
  refresh-token-validity-in-seconds: 1209600 # 14 days

springdoc:
  swagger-ui:
    url: https://api.dddstudy.site/v3/api-docs
    oauth2-redirect-url: https://api.dddstudy.site/swagger-ui/oauth2-redirect.html
